version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: clinic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpassword
      POSTGRES_DB: clinic_app
    ports:
      - "5433:5432"
    volumes:
      - clinic_postgres_data:/var/lib/postgresql/data

volumes:
  clinic_postgres_data:
